### ISSUE TITLE
请问:LoadAudio和SaveAudio来源于哪个插件?

### ISSUE THREAD

**Issue by peizhiluo007** [SpenserCai/ComfyUI-FunAudioLLM#13]
这两个缺失，请问需要再安装哪个插件?
十分感谢！

**Comment by peizhiluo007** [comment]
没找到直接能用的。但是有类似的，稍微理了下。
又需要的可以参考 :
https://github.com/peizhiluo007/CosyVoice-ComfyUI

**Comment by SpenserCai** [comment]
这两个是ComfyUi自带的节点，你需要把ComfyUi更新到最新版本。
