### ISSUE TITLE
No module named 'matcha.models'; 'matcha' is not a package

### ISSUE THREAD

**Issue by Lumoria** [SpenserCai/ComfyUI-FunAudioLLM#8]
When running I get the following error:

`pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package
`

**Comment by Lumoria** [comment]
In the original repo, they say to fix this error we `export PYTHONPATH=third_party/Matcha-TTS` , but where is Matcha-TTS supposed to be located for this custom node to work?

**Comment by Lumoria** [comment]
Nevermind, problem was solved after running `pip install matcha-tts`

**Comment by Lumoria** [comment]
Nevermind, problem was solved after running `pip install matcha-tts`

**Comment by SpenserCai** [comment]
I am not sure if there will be any issues with the latest version of matcha tts, but I have already placed matcha in the directory according to CosyVoice's solution. Now it can be used normally without installing matcha tts through pip
