### ISSUE TITLE
Can a switch be added to force GPU use?

### ISSUE THREAD

**Issue by Lumoria** [SpenserCai/ComfyUI-FunAudioLLM#9]
When running I get the following warning: 

`2024-10-05 16:39:49.851404279 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 12 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2024-10-05 16:39:49.852288129 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-10-05 16:39:49.852294631 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.`

A block of text that takes 6 seconds on the original CosyVoice repo takes 20 seconds on this node because it seems to be only using the CPU.

**Comment by SpenserCai** [comment]
Judging from the error report, it may be caused by the non-match between the onnxruntime-gpu version and the cuda version. You can try to find the corresponding version for installation.

**Comment by Lumoria** [comment]
It seems like the required onnx version requires cuda 11.8. The original repo runs with this as well. But if I install this cuda version in my comfyUI I get a huge list of new errors. Are you using cuda 11.8 in an updated comfyUI?

**Comment by SpenserCai** [comment]
> It seems like the required onnx version requires cuda 11.8. The original repo runs with this as well. But if I install this cuda version in my comfyUI I get a huge list of new errors. Are you using cuda 11.8 in an updated comfyUI? 

I have been using cuda 11.8 for a long time. Onnxruntime-gpu seems to have other versions that support other versions of cuda.

**Comment by Lumoria** [comment]
> > It seems like the required onnx version requires cuda 11.8. The original repo runs with this as well. But if I install this cuda version in my comfyUI I get a huge list of new errors. Are you using cuda 11.8 in an updated comfyUI?
> 
> I have been using cuda 11.8 for a long time. Onnxruntime-gpu seems to have other versions that support other versions of cuda.

Yeah I've also tried various versions of onnxruntime-gpu that support a newer cuda version and it still throws errors about not being able to use the GPU..

**Comment by SpenserCai** [comment]
> > > It seems like the required onnx version requires cuda 11.8. The original repo runs with this as well. But if I install this cuda version in my comfyUI I get a huge list of new errors. Are you using cuda 11.8 in an updated comfyUI?
> > 
> > 
> > I have been using cuda 11.8 for a long time. Onnxruntime-gpu seems to have other versions that support other versions of cuda.
> 
> Yeah I've also tried various versions of onnxruntime-gpu that support a newer cuda version and it still throws errors about not being able to use the GPU..

![image](https://github.com/user-attachments/assets/62bca13c-5051-4ec6-9827-e8f725c68223)
This is the version information of my torch and onnxrruntime-gpu

**Comment by Lumoria** [comment]
> > > > It seems like the required onnx version requires cuda 11.8. The original repo runs with this as well. But if I install this cuda version in my comfyUI I get a huge list of new errors. Are you using cuda 11.8 in an updated comfyUI?
> > > 
> > > 
> > > I have been using cuda 11.8 for a long time. Onnxruntime-gpu seems to have other versions that support other versions of cuda.
> > 
> > 
> > Yeah I've also tried various versions of onnxruntime-gpu that support a newer cuda version and it still throws errors about not being able to use the GPU..
> 
> ![image](https://private-user-images.githubusercontent.com/25168945/373960733-62bca13c-5051-4ec6-9827-e8f725c68223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzc1MjgsIm5iZiI6MTcyODIzNzIyOCwicGF0aCI6Ii8yNTE2ODk0NS8zNzM5NjA3MzMtNjJiY2ExM2MtNTA1MS00ZWM2LTk4MjctZThmNzI1YzY4MjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE3NTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjNhOTliOWUzYzE1ODVhOTg2MzZmYjFmZjg4OWY2M2FjMDdkYjFkMWUzODZhMWIxOTFhOTcwM2FhZWRlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xX0qvf-kaFxaQYdsQ7nVE1bFMzRUxSLJOoBRMBL8EsA) This is the version information of my torch and onnxrruntime-gpu

Ok so I made a separate ComfyUI install that uses cuda 11.8 and all other modules match what you posted. I now get the following error: 
 `2024-10-06 15:00:49.839809415 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory`
 
 I have cudnn installed and libcudnn.so.8 is located in /usr/lib/. Is there not where it should be?

**Comment by SpenserCai** [comment]
> > > > > It seems like the required onnx version requires cuda 11.8. The original repo runs with this as well. But if I install this cuda version in my comfyUI I get a huge list of new errors. Are you using cuda 11.8 in an updated comfyUI?
> 
> > > > 
> 
> > > > 
> 
> > > > I have been using cuda 11.8 for a long time. Onnxruntime-gpu seems to have other versions that support other versions of cuda.
> 
> > > 
> 
> > > 
> 
> > > Yeah I've also tried various versions of onnxruntime-gpu that support a newer cuda version and it still throws errors about not being able to use the GPU..
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/25168945/373960733-62bca13c-5051-4ec6-9827-e8f725c68223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzc1MjgsIm5iZiI6MTcyODIzNzIyOCwicGF0aCI6Ii8yNTE2ODk0NS8zNzM5NjA3MzMtNjJiY2ExM2MtNTA1MS00ZWM2LTk4MjctZThmNzI1YzY4MjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE3NTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjNhOTliOWUzYzE1ODVhOTg2MzZmYjFmZjg4OWY2M2FjMDdkYjFkMWUzODZhMWIxOTFhOTcwM2FhZWRlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xX0qvf-kaFxaQYdsQ7nVE1bFMzRUxSLJOoBRMBL8EsA) This is the version information of my torch and onnxrruntime-gpu
> 
> 
> 
> Ok so I made a separate ComfyUI install that uses cuda 11.8 and all other modules match what you posted. I now get the following error: 
> 
>  `2024-10-06 15:00:49.839809415 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory`
> 
>  
> 
>  I have cudnn installed and libcudnn.so.8 is located in /usr/lib/. Is there not where it should be?

I think you need to use the export command in shell to set the path of cuda 11.8 and then run comfyui.

**Comment by drake7707** [comment]
Don't install onnxruntime and onnxruntime-gpu at the same time. I've had the same problem with a few nodes.

I made a script to fix it because some nodes seem to add onnxruntime back and then CPU will take precedence over GPU:

```
#!/bin/bash

pip uninstall --yes onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.19.2 --no-cache-dir
```

Just uninstalling onnxruntime is not enough, that will leave it in a broken state, you have to uninstall both and then explicitly install onnxruntime-gpu
